export const testMessages = [
  {
    id: 1,
    roomId: "mia",
    channelId: "mia",
    body: "Hi!",
    ts: new Date('September 25, 2021 22:06:10'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 2,
    roomId: "Jack White",
    channelId: "Jack White",
    body: "This is Jack White, mister! Are you here?",
    ts: new Date('August 5, 2021 21:27:10'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 3,
    roomId: "Dave Grohl",
    channelId: "Dave Grohl",
    body: "Wazaaa!!!",
    ts: new Date('August 5, 2021 19:12:59'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 4,
    roomId: "Dave Grohl",
    channelId: "Dave Grohl",
    body: "This is Dave Grohl, dude!",
    ts: new Date('August 5, 2021 19:14:01'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 5,
    roomId: "Nath Williams",
    channelId: "Nath Williams",
    body: "What is up, bro! Heard you are doing very well, mister? Nice to hear! What\'s your plans on next weekends?",
    ts: new Date('August 5, 2021 23:05:45'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 6,
    roomId: "Nath Williams",
    channelId: "Nath Williams",
    body: "This is Nathan Williams from Wavves, dude!",
    ts: new Date('August 5, 2021 23:11:20'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 7,
    roomId: "mia",
    channelId: "mia",
    body: "Yo! Waz up there!",
    ts: new Date('September 25, 2021 22:06:29'),
    isOut: false,
    isUnread: true,
  },
  {
    id: 8,
    roomId: "Nath Williams",
    channelId: "Nath Williams",
    body: "Yooo! Waaaaz uuuup! :)))",
    ts: new Date('August 7, 2021 10:11:20'),
    isOut: true,
    isUnread: false,
  },
  {
    id: 9,
    roomId: "Nath Williams",
    channelId: "Nath Williams",
    body: "Yeah, man, everything is super cool!!! And what about you? I\' ve read your new album is out soon, right?",
    ts: new Date('August 7, 2021 10:15:20'),
    isOut: true,
    isUnread: false,
  },
  {
    id: 10,
    roomId: "Nath Williams",
    channelId: "Nath Williams",
    body: ":D",
    ts: new Date('August 7, 2021 10:16:20'),
    isOut: true,
    isUnread: false,
  },
];